import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { resolveCorpus } from "./corpus";
import { EMBEDDING_DIMENSION } from "./embeddings";
import type { EmbeddingsClient } from "./embeddings";
import { readEvents } from "./events";
import type { StoredEvent } from "./events";
import { initRepo, runGit } from "./git";
import { createServer } from "./mcp-server";
import { computeUseStats, formatUseStats } from "./stats-use";
import { serializePhaseDocument } from "./workflow/phase-document";

// The fixture log is GENERATED by the real write path — a live server, a real corpus, real
// workflow_step calls carrying real declarations — never assembled by hand. A hand-built log would
// only prove that this reader agrees with my idea of the producer; driving the producer proves they
// agree with each other.

const CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const LOGGED_AT = new Date("2026-09-01T10:00:00.000Z");
const fixedClock = () => LOGGED_AT;

function ulid(n: number): string {
  return "01ARZ3NDEKTSV4RRFFQ69G5F" + CROCKFORD[Math.floor(n / 32) % 32]! + CROCKFORD[n % 32]!;
}

function sequentialIds(): () => string {
  let counter = 0;
  return () => ulid(counter++);
}

function bagVector(text: string): Float32Array {
  const vector = new Float32Array(EMBEDDING_DIMENSION);
  for (const term of text.toLowerCase().match(/[a-z0-9]+/g) ?? []) {
    let hash = 2166136261;
    for (let index = 0; index < term.length; index++) {
      hash ^= term.charCodeAt(index);
      hash = Math.imul(hash, 16777619);
    }
    vector[(hash >>> 0) % EMBEDDING_DIMENSION] = vector[(hash >>> 0) % EMBEDDING_DIMENSION]! + 1;
  }
  return vector;
}

function bagClient(): EmbeddingsClient {
  return { embed: async (inputs) => ({ available: true, embeddings: inputs.map(bagVector), retries: 0 }) };
}

interface Bench {
  client: Client;
  projectRoot: string;
  corpusHome: string;
}

async function makeBench(): Promise<Bench> {
  const projectRoot = mkdtempSync(join(tmpdir(), "mneme-use-proj-"));
  await initRepo(projectRoot);
  mkdirSync(join(projectRoot, "src"), { recursive: true });
  writeFileSync(join(projectRoot, "src", "a.ts"), "export const a = 1;\n");
  await runGit(projectRoot, ["add", "."]);
  const committed = await runGit(projectRoot, [
    "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-q", "-m", "init",
  ]);
  if (committed.exitCode !== 0) throw new Error(committed.stderr);
  const corpusHome = mkdtempSync(join(tmpdir(), "mneme-use-home-"));
  const server = createServer({
    projectRoot,
    corpusHome,
    embeddings: bagClient(),
    idFactory: sequentialIds(),
    clock: fixedClock,
  });
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  const client = new Client({ name: "test-client", version: "0.0.0" });
  await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
  return { client, projectRoot, corpusHome };
}

async function callText(bench: Bench, name: string, args: Record<string, unknown>): Promise<string> {
  const result = await bench.client.callTool({ name, arguments: args });
  return (result.content as Array<{ type: string; text: string }>).map((part) => part.text).join("\n");
}

async function loggedEvents(bench: Bench): Promise<StoredEvent[]> {
  const corpus = await resolveCorpus(bench.projectRoot, { corpusHome: bench.corpusHome });
  return readEvents(corpus.eventsDir);
}

const PROBE_DESCRIPTION = "ranking probe module evidence window closure";

function probePhase(id: string): string {
  return serializePhaseDocument({
    id,
    deps: [],
    agentRole: "coder",
    description: PROBE_DESCRIPTION,
    tasks: ["do the work"],
    doneWhen: [{ kind: "executable", description: "green", command: "true" }],
    knowledge: [],
  });
}

async function acceptNote(bench: Bench, body: string): Promise<string> {
  const staged = await callText(bench, "remember", { type: "decision", body, anchors: ["src/a.ts"] });
  const noteId = /Staged note ([0-9a-fA-F-]{36}|[0-9A-Z]{26})/.exec(staged)?.[1];
  if (noteId === undefined) throw new Error(`could not read the staged note id from: ${staged}`);
  await callText(bench, "staging_resolve", { id: noteId, decision: "accept" });
  return noteId;
}

async function startRun(bench: Bench, phaseId: string): Promise<string> {
  const started = await callText(bench, "workflow_start", {
    phases: [probePhase(phaseId)],
    steps: [{ id: "implement", max_attempts: 1, on_fail: { action: "escalate" } }],
    max_iterations: 10,
  });
  const runId = /Started workflow run ([0-9a-fA-F-]{36}|[0-9A-Z]{26})/.exec(started)?.[1];
  if (runId === undefined) throw new Error(`could not read the run id from: ${started}`);
  return runId;
}

// One full phase: recall (compiling a real bundle), a green step, and a harvest that may or may not
// carry a declaration.
async function walkPhase(
  bench: Bench,
  phaseId: string,
  usedNotes: Array<{ id: string; evidence: string }> | undefined,
): Promise<void> {
  const runId = await startRun(bench, phaseId);
  await callText(bench, "workflow_step", {});
  await callText(bench, "workflow_step", {
    run_id: runId,
    step_result: { phase_id: phaseId, step_id: "implement", attempt: 1, outcome: "success" },
  });
  const harvest: Record<string, unknown> = { run_id: runId, harvest_artifacts: [] };
  if (usedNotes !== undefined) harvest["used_notes"] = usedNotes;
  await callText(bench, "workflow_step", harvest);
}

describe("precision-of-use over a log the engine itself wrote", () => {
  test("a declared note counts as used against the bundle that surfaced it", async () => {
    const bench = await makeBench();
    const noteId = await acceptNote(bench, "Decision: the ranking probe module closes its evidence window");
    await walkPhase(bench, "phase-one", [{ id: noteId, evidence: "its window rule shaped the closure check" }]);

    const summary = computeUseStats(await loggedEvents(bench), LOGGED_AT);

    expect(summary.allTime.overall).toEqual({ bundled: 1, used: 1 });
    expect(summary.allTime.byType["decision"]).toEqual({ bundled: 1, used: 1 });
    expect(summary.coverage).toEqual({ harvests: 1, instrumented: 1 });
    expect(formatUseStats(summary)).toContain("1/1 (100%)");
  });

  test("a surfaced note nobody declared sits in the denominator, not the numerator", async () => {
    const bench = await makeBench();
    const used = await acceptNote(bench, "Decision: the ranking probe module closes its evidence window");
    await acceptNote(bench, "Decision: the ranking probe module also logs its window boundaries");
    await walkPhase(bench, "phase-one", [{ id: used, evidence: "its window rule shaped the closure check" }]);

    const summary = computeUseStats(await loggedEvents(bench), LOGGED_AT);

    expect(summary.allTime.overall).toEqual({ bundled: 2, used: 1 });
    expect(formatUseStats(summary)).toContain("1/2 (50%)");
  });

  test("an uninstrumented harvest leaves the precision population entirely and shows in coverage", async () => {
    const bench = await makeBench();
    const noteId = await acceptNote(bench, "Decision: the ranking probe module closes its evidence window");
    await walkPhase(bench, "phase-one", [{ id: noteId, evidence: "its window rule shaped the closure check" }]);
    await walkPhase(bench, "phase-two", undefined);

    const summary = computeUseStats(await loggedEvents(bench), LOGGED_AT);

    // The second phase surfaced the same note, but its harvest said nothing — so it contributes to
    // neither side of the ratio.
    expect(summary.allTime.overall).toEqual({ bundled: 1, used: 1 });
    expect(summary.coverage).toEqual({ harvests: 2, instrumented: 1 });
    expect(formatUseStats(summary)).toContain("1/2 harvests declared usage (50%)");
  });

  test("an explicit empty declaration IS instrumented and scores an honest zero", async () => {
    const bench = await makeBench();
    await acceptNote(bench, "Decision: the ranking probe module closes its evidence window");
    await walkPhase(bench, "phase-one", []);

    const summary = computeUseStats(await loggedEvents(bench), LOGGED_AT);

    expect(summary.allTime.overall).toEqual({ bundled: 1, used: 0 });
    expect(summary.coverage).toEqual({ harvests: 1, instrumented: 1 });
    expect(formatUseStats(summary)).toContain("0/1 (0%)");
  });

  test("a log with no declaration at all reports NO DATA, never a zero percent", async () => {
    const bench = await makeBench();
    await acceptNote(bench, "Decision: the ranking probe module closes its evidence window");
    await walkPhase(bench, "phase-one", undefined);

    const rendered = formatUseStats(computeUseStats(await loggedEvents(bench), LOGGED_AT));

    // Precision has NO DATA — nobody declared anything, which is not the same as "nothing helped".
    // Coverage, by contrast, honestly reports 0%: a harvest did happen and it declared nothing.
    const precisionLines = rendered.split("\n").filter((line) => line.includes("Precision-of-use"));
    expect(precisionLines.length).toBe(3);
    for (const line of precisionLines) {
      expect(line).toContain("no data");
      expect(line).not.toContain("%");
    }
    expect(rendered).toContain("0/1 harvests declared usage (0%)");
  });
});

describe("calendar windows are calendar windows", () => {
  async function declaredLog(): Promise<StoredEvent[]> {
    const bench = await makeBench();
    const noteId = await acceptNote(bench, "Decision: the ranking probe module closes its evidence window");
    await walkPhase(bench, "phase-one", [{ id: noteId, evidence: "its window rule shaped the closure check" }]);
    return loggedEvents(bench);
  }

  function windowOf(summary: ReturnType<typeof computeUseStats>, days: number) {
    return summary.windows.find((window) => window.days === days)!;
  }

  test("a fresh declaration falls inside both windows", async () => {
    const summary = computeUseStats(await declaredLog(), new Date(LOGGED_AT.getTime() + 24 * 60 * 60_000));

    expect(windowOf(summary, 30).overall).toEqual({ bundled: 1, used: 1 });
    expect(windowOf(summary, 90).overall).toEqual({ bundled: 1, used: 1 });
  });

  // A corpus that slept for half a year must SAY so. Anchoring the windows on the log's own newest
  // event would slide the horizon along with the silence and report a busy 30 days that never were.
  test("a sleeping corpus empties its windows while all-time keeps the history", async () => {
    const events = await declaredLog();
    const halfAYearLater = new Date(LOGGED_AT.getTime() + 180 * 24 * 60 * 60_000);

    const summary = computeUseStats(events, halfAYearLater);

    expect(windowOf(summary, 30).overall).toEqual({ bundled: 0, used: 0 });
    expect(windowOf(summary, 90).overall).toEqual({ bundled: 0, used: 0 });
    expect(summary.allTime.overall).toEqual({ bundled: 1, used: 1 });
    expect(formatUseStats(summary)).toContain("last 30 days: no data");
  });

  test("the same log and the same instant render byte-for-byte the same report", async () => {
    const events = await declaredLog();

    expect(formatUseStats(computeUseStats(events, LOGGED_AT))).toBe(
      formatUseStats(computeUseStats(events, LOGGED_AT)),
    );
  });
});

describe("the reader survives a log older than the metric", () => {
  test("applications without the v16 keys contribute nothing and throw nothing", async () => {
    const bench = await makeBench();
    await acceptNote(bench, "Decision: the ranking probe module closes its evidence window");
    await walkPhase(bench, "phase-one", undefined);
    // Strip the v16 keys from every workflow application, exactly as a pre-v16 log would have them.
    const legacy = (await loggedEvents(bench)).map((event) => {
      if (event.type !== "workflow_step_applied") return event;
      const { bundle_notes: _bundle, used_notes: _used, ...rest } = event;
      return rest as StoredEvent;
    });

    const summary = computeUseStats(legacy, LOGGED_AT);

    expect(summary.allTime.overall).toEqual({ bundled: 0, used: 0 });
    expect(summary.coverage.instrumented).toBe(0);
    expect(formatUseStats(summary)).toContain("no data");
  });
});
